version: "3.9"

services:
    postgres:
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      env_file:
        ./.env 
      networks:
        - awesome

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4:4.18
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: secret
        PGADMIN_LISTEN_PORT: 80
      env_file:
        ./.env
      ports:
        - "8080:80"
      volumes:
        - ./tmp/pgadmin-data:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - awesome

    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
          POSTGRES_HOST: postgres
        env_file:
          ./.env 
        depends_on:
          - postgres
        networks:
          - awesome

    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:3000"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}
          - EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL}
          - INTERNAL_SERVER_URL=${INTERNAL_SERVER_URL}
        env_file:
          ./.env 
        networks:
          - awesome

networks:
  awesome:
      driver: bridge 


